
services:
  gateway:
    build: .
    container_name: gateway
    env_file: .env
    command: npm run start:gateway
    environment:
      DATABASE_URL: "${DATABASE_URL}"
      DIRECT_URL: "${DIRECT_URL}"
      PRISMA_SCHEMA_ENGINE_URL: "${PRISMA_SCHEMA_ENGINE_URL}"
      REDIS_URL: "${REDIS_URL}"
      REDIS_HOST: "${REDIS_HOST}"
      REDIS_PORT: "${REDIS_PORT}"
      REDIS_USERNAME: "${REDIS_USERNAME}"
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
      JWT_SECRET: "${JWT_SECRET}"
      NODE_ENV: "${NODE_ENV}"
      FRONTEND_URL: "${FRONTEND_URL}"
      OPENROUTESERVICE_API_KEY: "${OPENROUTESERVICE_API_KEY}"
      CLOUDINARY_CLOUD_NAME: "${CLOUDINARY_CLOUD_NAME}"
      CLOUDINARY_API_KEY: "${CLOUDINARY_API_KEY}"
      CLOUDINARY_API_SECRET: "${CLOUDINARY_API_SECRET}"
      EMAIL_PORT: "${EMAIL_PORT}"
      EMAIL_HOST: "${EMAIL_HOST}"
      EMAIL_SECURE: "${EMAIL_SECURE}"
      EMAIL_USER: "${EMAIL_USER}"
      EMAIL_PASSWORD: "${EMAIL_PASSWORD}"
      EMAIL_CLIENT_ID: "${EMAIL_CLIENT_ID}"
      EMAIL_CLIENT_SECRET: "${EMAIL_CLIENT_SECRET}"
      EMAIL_REFRESH_TOKEN: "${EMAIL_REFRESH_TOKEN}"
      EMAIL_FROM: "${EMAIL_FROM}"
      OCR_SPACE_KEY: "${OCR_SPACE_KEY}"
    ports:
      - "3000:3000"

  auth:
    build: .
    container_name: auth
    env_file: .env
    command: npm run start:auth
    environment:
      DATABASE_URL: "${DATABASE_URL}"
      DIRECT_URL: "${DIRECT_URL}"
      PRISMA_SCHEMA_ENGINE_URL: "${PRISMA_SCHEMA_ENGINE_URL}"
      REDIS_URL: "${REDIS_URL}"
      REDIS_HOST: "${REDIS_HOST}"
      REDIS_PORT: "${REDIS_PORT}"
      REDIS_USERNAME: "${REDIS_USERNAME}"
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
      JWT_SECRET: "${JWT_SECRET}"
      NODE_ENV: "${NODE_ENV}"
      FRONTEND_URL: "${FRONTEND_URL}"
      OPENROUTESERVICE_API_KEY: "${OPENROUTESERVICE_API_KEY}"
      CLOUDINARY_CLOUD_NAME: "${CLOUDINARY_CLOUD_NAME}"
      CLOUDINARY_API_KEY: "${CLOUDINARY_API_KEY}"
      CLOUDINARY_API_SECRET: "${CLOUDINARY_API_SECRET}"
      EMAIL_PORT: "${EMAIL_PORT}"
      EMAIL_HOST: "${EMAIL_HOST}"
      EMAIL_SECURE: "${EMAIL_SECURE}"
      EMAIL_USER: "${EMAIL_USER}"
      EMAIL_PASSWORD: "${EMAIL_PASSWORD}"
      EMAIL_CLIENT_ID: "${EMAIL_CLIENT_ID}"
      EMAIL_CLIENT_SECRET: "${EMAIL_CLIENT_SECRET}"
      EMAIL_REFRESH_TOKEN: "${EMAIL_REFRESH_TOKEN}"
      EMAIL_FROM: "${EMAIL_FROM}"
      OCR_SPACE_KEY: "${OCR_SPACE_KEY}"

  user:
    build: .
    container_name: user
    env_file: .env
    command: npm run start:user
    environment:
      DATABASE_URL: "${DATABASE_URL}"
      DIRECT_URL: "${DIRECT_URL}"
      PRISMA_SCHEMA_ENGINE_URL: "${PRISMA_SCHEMA_ENGINE_URL}"
      REDIS_URL: "${REDIS_URL}"
      REDIS_HOST: "${REDIS_HOST}"
      REDIS_PORT: "${REDIS_PORT}"
      REDIS_USERNAME: "${REDIS_USERNAME}"
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
      JWT_SECRET: "${JWT_SECRET}"
      NODE_ENV: "${NODE_ENV}"
      FRONTEND_URL: "${FRONTEND_URL}"
      OPENROUTESERVICE_API_KEY: "${OPENROUTESERVICE_API_KEY}"
      CLOUDINARY_CLOUD_NAME: "${CLOUDINARY_CLOUD_NAME}"
      CLOUDINARY_API_KEY: "${CLOUDINARY_API_KEY}"
      CLOUDINARY_API_SECRET: "${CLOUDINARY_API_SECRET}"
      EMAIL_PORT: "${EMAIL_PORT}"
      EMAIL_HOST: "${EMAIL_HOST}"
      EMAIL_SECURE: "${EMAIL_SECURE}"
      EMAIL_USER: "${EMAIL_USER}"
      EMAIL_PASSWORD: "${EMAIL_PASSWORD}"
      EMAIL_CLIENT_ID: "${EMAIL_CLIENT_ID}"
      EMAIL_CLIENT_SECRET: "${EMAIL_CLIENT_SECRET}"
      EMAIL_REFRESH_TOKEN: "${EMAIL_REFRESH_TOKEN}"
      EMAIL_FROM: "${EMAIL_FROM}"
      OCR_SPACE_KEY: "${OCR_SPACE_KEY}"

  fulfillment:
    build: .
    container_name: fulfillment
    env_file: .env
    command: npm run start:fulfillment
    environment:
      DATABASE_URL: "${DATABASE_URL}"
      DIRECT_URL: "${DIRECT_URL}"
      PRISMA_SCHEMA_ENGINE_URL: "${PRISMA_SCHEMA_ENGINE_URL}"
      REDIS_URL: "${REDIS_URL}"
      REDIS_HOST: "${REDIS_HOST}"
      REDIS_PORT: "${REDIS_PORT}"
      REDIS_USERNAME: "${REDIS_USERNAME}"
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
      JWT_SECRET: "${JWT_SECRET}"
      NODE_ENV: "${NODE_ENV}"
      FRONTEND_URL: "${FRONTEND_URL}"
      OPENROUTESERVICE_API_KEY: "${OPENROUTESERVICE_API_KEY}"
      CLOUDINARY_CLOUD_NAME: "${CLOUDINARY_CLOUD_NAME}"
      CLOUDINARY_API_KEY: "${CLOUDINARY_API_KEY}"
      CLOUDINARY_API_SECRET: "${CLOUDINARY_API_SECRET}"
      EMAIL_PORT: "${EMAIL_PORT}"
      EMAIL_HOST: "${EMAIL_HOST}"
      EMAIL_SECURE: "${EMAIL_SECURE}"
      EMAIL_USER: "${EMAIL_USER}"
      EMAIL_PASSWORD: "${EMAIL_PASSWORD}"
      EMAIL_CLIENT_ID: "${EMAIL_CLIENT_ID}"
      EMAIL_CLIENT_SECRET: "${EMAIL_CLIENT_SECRET}"
      EMAIL_REFRESH_TOKEN: "${EMAIL_REFRESH_TOKEN}"
      EMAIL_FROM: "${EMAIL_FROM}"
      OCR_SPACE_KEY: "${OCR_SPACE_KEY}"

  notification:
    build: .
    container_name: notification
    env_file: .env
    command: npm run start:notification
    environment:
      DATABASE_URL: "${DATABASE_URL}"
      DIRECT_URL: "${DIRECT_URL}"
      PRISMA_SCHEMA_ENGINE_URL: "${PRISMA_SCHEMA_ENGINE_URL}"
      REDIS_URL: "${REDIS_URL}"
      REDIS_HOST: "${REDIS_HOST}"
      REDIS_PORT: "${REDIS_PORT}"
      REDIS_USERNAME: "${REDIS_USERNAME}"
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
      JWT_SECRET: "${JWT_SECRET}"
      NODE_ENV: "${NODE_ENV}"
      FRONTEND_URL: "${FRONTEND_URL}"
      OPENROUTESERVICE_API_KEY: "${OPENROUTESERVICE_API_KEY}"
      CLOUDINARY_CLOUD_NAME: "${CLOUDINARY_CLOUD_NAME}"
      CLOUDINARY_API_KEY: "${CLOUDINARY_API_KEY}"
      CLOUDINARY_API_SECRET: "${CLOUDINARY_API_SECRET}"
      EMAIL_PORT: "${EMAIL_PORT}"
      EMAIL_HOST: "${EMAIL_HOST}"
      EMAIL_SECURE: "${EMAIL_SECURE}"
      EMAIL_USER: "${EMAIL_USER}"
      EMAIL_PASSWORD: "${EMAIL_PASSWORD}"
      EMAIL_CLIENT_ID: "${EMAIL_CLIENT_ID}"
      EMAIL_CLIENT_SECRET: "${EMAIL_CLIENT_SECRET}"
      EMAIL_REFRESH_TOKEN: "${EMAIL_REFRESH_TOKEN}"
      EMAIL_FROM: "${EMAIL_FROM}"
      OCR_SPACE_KEY: "${OCR_SPACE_KEY}"
