export const PATTERNS = {
  AUTH_REGISTER: 'auth.register',
  AUTH_LOGIN: 'auth.login',
  AUTH_REFRESH_TOKEN: 'auth.refresh_token',
  AUTH_CHANGE_PASSWORD: 'auth.change_password',

  USER_CREATE: 'user.create',
  USER_FIND_BY_ID: 'user.findById',
  USER_FIND_ALL: 'user.findAll',
  USER_UPDATE: 'user.update',
  USER_DELETE: 'user.delete',
  USER_FIND_BY_EMAIL: 'user.findByEmail',
  USER_CHANGE_ROLE: 'user.changeRole',

  STAFF_CREATE: 'staff.register',
  STAFF_DELETE: 'staff.delete',
  STAFF_FIND_ALL: 'staff.findAll',
  STAFF_FIND_BY_ROLE: 'staff.findByRole',
  STAFF_FIND_BY_ID: 'staff.findById',
  STAFF_UPDATE: 'staff.update',
  STAFF_FIND_BY_BRANCH: 'staff.findByBranch',
  STAFF_ASSIGN_BRANCH: 'staff.assignBranch',

  BRANCH_CREATE: 'branch.create',
  BRANCH_FIND_BY_ID: 'branch.findById',
  BRANCH_FIND_ALL: 'branch.findAll',
  BRANCH_UPDATE: 'branch.update',
  BRANCH_DELETE: 'branch.delete',
  BRANCH_ASSIGN_MANAGER: 'branch.assignManager',
  BRANCH_REVOKE_MANAGER: 'branch.revokeManager',

  ROLE_CREATE: 'role.create',
  ROLE_FIND_BY_ID_OR_NAME: 'role.findByIdOrName',
  ROLE_FIND_ALL: 'role.findAll',
  ROLE_UPDATE: 'role.update',
  ROLE_DELETE: 'role.delete',
  ROLE_FIND_BY_ID: 'role.findById',
  ROLE_ASSIGN_PERMISSIONS: 'role.assignPermissions',
  ROLE_REMOVE_PERMISSION: 'role.removePermission',
  ROLE_UPDATE_PERMISSION: 'role.updatePermission',
  ROLE_ASSIGN_USER: 'role.assignUser',

  // ===== PERMISSION =====
  PERMISSION_CREATE: 'permission.create',
  PERMISSION_FIND_BY_ID: 'permission.findById',
  PERMISSION_FIND_ALL: 'permission.findAll',
  PERMISSION_UPDATE: 'permission.update',
  PERMISSION_DELETE: 'permission.delete',

  // Fleet / Vehicle patterns
  FLEET_CREATE_VEHICLE: 'fleet.createVehicle',
  FLEET_GET_ALL_VEHICLES: 'fleet.getAllVehicles',
  FLEET_GET_VEHICLE_BY_ID: 'fleet.getVehicleById',
  FLEET_UPDATE_VEHICLE: 'fleet.updateVehicle',
  FLEET_DELETE_VEHICLE: 'fleet.deleteVehicle',
  FLEET_ASSIGN_VEHICLE: 'fleet.assignVehicle',
  FLEET_UNASSIGN_VEHICLE: 'fleet.unassignVehicle',
  FLEET_GET_DRIVER_VEHICLES: 'fleet.getVehiclesByDriver',
  FLEET_LOG_MAINTENANCE: 'fleet.logMaintenance',
  FLEET_GET_MAINTENANCE_HISTORY: 'fleet.getMaintenanceHistory',
  FLEET_GET_LATEST_MAINTENANCE: 'fleet.getLatestMaintenance',
  FLEET_GET_SUMMARY: 'fleet.getFleetSummary',
  FLEET_GET_STATUS_SUMMARY: 'fleet.getVehicleStatusSummary',
  FLEET_GET_AVAILABLE_VEHICLES: 'fleet.getAvailableVehicles',
  FLEET_GET_VEHICLE_HISTORY: 'fleet.getVehicleHistory',
  FLEET_RETIRE_VEHICLE: 'fleet.retireVehicle',
  FLEET_GET_ALERTS: 'fleet.getFleetAlerts',
  FLEET_GET_DRIVER_HISTORY: 'fleet.getDriverVehicleHistory',
} as const;
