export const PATTERNS = {
  AUTH_REGISTER: 'auth.register',
  AUTH_LOGIN: 'auth.login',
  AUTH_LOGIN_MOBILE: 'auth.login_mobile',
  AUTH_REFRESH_TOKEN: 'auth.refresh_token',
  AUTH_CHANGE_PASSWORD: 'auth.change_password',

  USER_CREATE: 'user.create',
  USER_FIND_BY_ID: 'user.findById',
  USER_FIND_ALL: 'user.findAll',
  USER_UPDATE: 'user.update',
  USER_DELETE: 'user.delete',
  USER_FIND_BY_EMAIL: 'user.findByEmail',
  USER_CHANGE_ROLE: 'user.changeRole',

  ADDRESS_CREATE: 'address.create',
  ADDRESS_LIST: 'address.list',
  ADDRESS_UPDATE: 'address.update',
  ADDRESS_DELETE: 'address.delete',
  PREFERENCES_UPDATE: 'preferences.update',
  CORPORATEINFO_UPDATE: 'corporate.update',

  STAFF_CREATE: 'staff.register',
  STAFF_DELETE: 'staff.delete',
  STAFF_FIND_ALL: 'staff.findAll',
  STAFF_FIND_BY_ROLE: 'staff.findByRole',
  STAFF_FIND_BY_ID: 'staff.findById',
  STAFF_UPDATE: 'staff.update',
  STAFF_FIND_BY_BRANCH: 'staff.findByBranch',
  STAFF_ASSIGN_BRANCH: 'staff.assignBranch',

  BRANCH_CREATE: 'branch.create',
  BRANCH_FIND_BY_ID: 'branch.findById',
  BRANCH_FIND_ALL: 'branch.findAll',
  BRANCH_UPDATE: 'branch.update',
  BRANCH_DELETE: 'branch.delete',
  BRANCH_ASSIGN_MANAGER: 'branch.assignManager',
  BRANCH_REVOKE_MANAGER: 'branch.revokeManager',

  ROLE_CREATE: 'role.create',
  ROLE_FIND_BY_ID_OR_NAME: 'role.findByIdOrName',
  ROLE_FIND_ALL: 'role.findAll',
  ROLE_UPDATE: 'role.update',
  ROLE_DELETE: 'role.delete',
  ROLE_FIND_BY_ID: 'role.findById',
  ROLE_ASSIGN_PERMISSIONS: 'role.assignPermissions',
  ROLE_REMOVE_PERMISSION: 'role.removePermission',
  ROLE_UPDATE_PERMISSION: 'role.updatePermission',
  ROLE_ASSIGN_USER: 'role.assignUser',

  // ===== PERMISSION =====
  PERMISSION_CREATE: 'permission.create',
  PERMISSION_FIND_BY_ID: 'permission.findById',
  PERMISSION_FIND_ALL: 'permission.findAll',
  PERMISSION_UPDATE: 'permission.update',
  PERMISSION_DELETE: 'permission.delete',

  // Fleet / Vehicle patterns
  FLEET_CREATE_VEHICLE: 'fleet.createVehicle',
  FLEET_GET_ALL_VEHICLES: 'fleet.getAllVehicles',
  FLEET_GET_VEHICLE_BY_ID: 'fleet.getVehicleById',
  FLEET_UPDATE_VEHICLE: 'fleet.updateVehicle',
  FLEET_DELETE_VEHICLE: 'fleet.deleteVehicle',
  FLEET_ASSIGN_VEHICLE: 'fleet.assignVehicle',
  FLEET_UNASSIGN_VEHICLE: 'fleet.unassignVehicle',
  FLEET_GET_DRIVER_VEHICLES: 'fleet.getVehiclesByDriver',
  FLEET_LOG_MAINTENANCE: 'fleet.logMaintenance',
  FLEET_GET_MAINTENANCE_HISTORY: 'fleet.getMaintenanceHistory',
  FLEET_GET_LATEST_MAINTENANCE: 'fleet.getLatestMaintenance',
  FLEET_GET_SUMMARY: 'fleet.getFleetSummary',
  FLEET_GET_STATUS_SUMMARY: 'fleet.getVehicleStatusSummary',
  FLEET_GET_AVAILABLE_VEHICLES: 'fleet.getAvailableVehicles',
  FLEET_GET_VEHICLE_HISTORY: 'fleet.getVehicleHistory',
  FLEET_RETIRE_VEHICLE: 'fleet.retireVehicle',
  FLEET_GET_ALERTS: 'fleet.getFleetAlerts',
  FLEET_GET_DRIVER_HISTORY: 'fleet.getDriverVehicleHistory',

  //Order Management System
  ORDER_CREATE: 'order.create',
  ORDER_FIND_BY_ID: 'order.findById',
  ORDER_FIND_ALL: 'order.findAll',
  ORDER_FIND_BY_CUSTOMER: 'order.findByCustomer',
  ORDER_FIND_BY_DRIVER: 'order.findByDriver',
  ORDER_FIND_BY_STATUS: 'order.findByStatus',
  ORDER_FIND_BY_BRANCH: 'order.findByBranch',
  ORDER_FIND_BY_TYPE: 'order.findByType',
  ORDER_FIND_BY_TRACK_CODE: 'order.findByTrackCode',
  ORDER_FIND_BY_PAYMENT: 'order.findByPayment',
  ORDER_FIND_BY_FULLFILLMENT: 'order.findByFullfillment',
  ORDER_UPDATE: 'order.update',
  ORDER_UPDATE_STATUS: 'order.updateStatus',
  ORDER_UPDATE_DRIVER: 'order.updateDriver',
  ORDER_UPDATE_TYPE: 'order.updateType',
  ORDER_DELETE: 'order.delete',
  ORDER_ACCEPT_DROP_OFF: 'order.acceptDropOff',
  ORDER_CONFIRM_PICKUP: 'order.confirmPickup',
  ORDER_VALIDATE: 'order.validate',
  ORDER_MARK_UNUSUAL: 'order.markUnusual',
  ORDER_APPROVE: 'order.approve',
  ORDER_FIND_FRAGILENT: 'order.getFragile',
  ORDER_FIND_PENDING: 'order.getPending',
  ORDER_FIND_PENDING_APPROVAL: 'order.getPendingApproval',
  ORDER_FIND_UNUSUAL: 'order.getUnusual',
  ORDER_FIND_PENDING_PICKUP: 'order.getPendingPickup',
  ORDER_CREATE_AND_VALIDATE: 'order.createAndValidate',
  ORDER_FIND_CATEGORICAL: 'order.getCategorical',
  ORDER_FIND_STATUS_LOG: 'order.getStatusLog',
  ORDER_CANCEL: 'order.cancel',
  ORDER_ADD_EXCEPTION: 'order.addException',
  ORDER_FIND_EXCEPTIONS: 'order.getExceptions',
  ORDER_REMOVE_EXCEPTION: 'order.removeException',
  
  //Dispatch Management System
  DISPATCH_CREATE: 'dispatch.create',
  DISPATCH_FIND_BY_ID: 'dispatch.findById',
  DISPATCH_FIND_ALL: 'dispatch.findAll',
  DISPATCH_FIND_BY_DRIVER: 'dispatch.findByDriver',
  DISPATCH_FIND_BY_STATUS: 'dispatch.findByStatus',
  DISPATCH_FIND_BY_BRANCH: 'dispatch.findByBranch',
  DISPATCH_FIND_BY_TYPE: 'dispatch.findByType',
  DISPATCH_FIND_BY_TRACK_CODE: 'dispatch.findByTrackCode',
  DISPATCH_FIND_BY_PAYMENT: 'dispatch.findByPayment',
  DISPATCH_UPDATE: 'dispatch.update',
  DISPATCH_APPROVE_CATEGORIZATION: 'dispatch.approveCategorization',
  DISPATCH_ASSIGN_DRIVER_FOR_PICKUP: 'dispatch.assignDriverForPickup',
  DISPATCH_ASSIGN_DRIVER_FOR_DELIVERY: 'dispatch.assignDriverForDelivery',
  DISPATCH_REMOVE_DRIVER_FROM_ORDER: 'dispatch.removeDriverFromOrder',
  DISPATCH_CHANGE_DRIVER_FOR_ORDER: 'dispatch.changeDriverForOrder',
  DISPATCH_CREATE_BATCH_DISPATCH: 'dispatch.createBatchDispatch',
  DISPATCH_ADD_ORDERS_TO_BATCH: 'dispatch.addOrdersToBatch',
  DISPATCH_ASSIGN_DRIVER_TO_BATCH: 'dispatch.assignDriverToBatch',
  DISPATCH_ASSIGN_OFFICER_TO_BATCH: 'dispatch.assignOfficerToBatch',
  DISPATCH_COLLECT_BATCH_BY_CARGO_OFFICER: 'dispatch.collectBatchByCargoOfficer',
  DISPATCH_HAND_OVER_BATCHES_TO_AIRPORT: 'dispatch.handoverBatchesToAirport',
  DISPATCH_COLLECT_FROM_AIRPORT: 'dispatch.collectFromAirport',
  DISPATCH_COMPARE_SCANNED_ORDERS: 'dispatch.compareScannedOrders',
  DISPATCH_CONFIRM_ARRIVAL_AND_HANDOVER: 'dispatch.confirmArrivalAndHandover',
  DISPATCH_ACCEPT_LAST_MILE_DELIVERY: 'dispatch.acceptLastMileDelivery',
  DISPATCH_COMPLETE_DELIVERY: 'dispatch.completeDelivery',


} as const;
